---
title: "Lab 10 - Exploratory Data Analysis"
author: "Anna Palmqvist Sjövall"
date: "9 oktober 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Use data iris
```{r}
library(datasets)
head(iris)
```
# Plot
```{r}
#Plot for all numerical columns
plot(iris$Sepal.Length, type='l')
plot(iris$Sepal.Width, type='l')
plot(iris$Petal.Length, type='l')
plot(iris$Petal.Width, type='l')

names <- colnames(iris)

#Create plots for all possible combinations of all columns
for (i in 1:4) {
  for (j in (i+1):5) {
    plot(iris[,i], iris[,j], xlab=names[i], ylab = names[j])
  }
}
```

# Barplot
```{r}
#Create a Bar Chart for minimum, maximum, median and average for all numerical columns
max <- apply(iris[, 1:4], 2, max) 
min <- apply(iris[, 1:4], 2, min)
median <- apply(iris[, 1:4], 2, median)
average <- apply(iris[, 1:4], 2, mean)

bar_names <- c('min', 'max', 'median', 'average')

for (i in 1:4) {
  barplot(c(min[i], max[i], median[i], average[i]), names.arg = bar_names, main = names[i])
}

#Sum up the minimum, maximum, median and average of all numerical columns and create a Bar Chart for each one.
sum_data <- apply(data.frame(max, min, median, average), 2, sum)
barplot(sum_data, main='Sum: minimum, maximum, median and average')

#Create a Bar Chart for each category in categorical column.
barplot(table(iris$Species))

#Create a Bar Chart for each category in categorical column with regard to each numerical column as follows: (data= sum (min value to average value)), ( data= sum (min value to median value), (data= sum (median value to max value).

bar_chart <- function(data, species) {
  bar_names <- c("min avg", "min med", "med max")
  for(i in 1:4) {
    main_name <- paste(species, ": ", names[i])
      
    min_avg <- sum(data[,i][which(min[i] < data[,i] & data[,i] < average[i])])
    min_med <- sum(data[,i][which(min[i] < data[,i] & data[,i] < median[i])])
    med_max <- sum(data[,i][which(median[i] < data[,i] & data[,i] < max[i])])
    
    barplot(c(min_avg, min_med, med_max), main=main_name, names.arg = bar_names)
  }
}

species <- unique(iris$Species)
for(i in 1:3){
  bar_chart(iris[which(iris$Species == species[i]),], species[i])
}

```


# Hist
```{r}
#Create histograms for each numerical column.
for (i in 1:4) {
  hist(iris[,i], xlab=names[i], main="Histogram")
}
```

# Boxplot
```{r}
#Create separate Box Plots for each numerical column.
for (i in 1:4) {
  boxplot(iris[,i], xlab=names[i])
}
```

# Pie
```{r}
#Create a pie chart for the categorical column
pie(table(iris$Species))

#Create a pie chart for each numerical column as follows: (min < data < average), (min < data < median), (median < data < max).

#Returns the amount of rows which fufill the condition
sort <- function(i, less, more) {
  length(iris[,i][which(less[i] < iris[,i] & iris[,i] < more[i])])
}

pie_names <- c('min<data<average', 'min<data<median', 'median<data<max')

for(i in 1:4) {
  min_avg <- (sort(i, min, average))
  min_med <- (sort(i, min, median))
  med_max <- (sort(i, median, max))
  pie(c(min_avg, min_med, med_max), labels=pie_names, main=names[i])
}

```


